# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'First Workflow'
        # Default value if no value is explicitly provided
        default: 'Hi'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Step 1 Complete!"
      run: echo "Step 2 Complete!"

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Cowsays
    uses: mscoutermarsh/cowsays-action@v1
    with:
    # What does the cow say?
    text: # optional, default is Ship it!!!!!
    # Color of your cow
    color: # optional, default is white
              
